# Generated by Django 2.0.1 on 2018-10-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'ordering': ('name',),
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('url_at_shop', models.URLField(verbose_name='Ссылка на товар в магазине')),
                ('main_image_url', models.URLField(verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'ordering': ('id',),
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Attribute', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристики товара',
                'ordering': ('-product__id', 'attribute__id'),
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Магазин',
                'ordering': ('name',),
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('site',), ('name',)},
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='store_app.ProductAttributes', to='store_app.Attribute', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Shop', verbose_name='Магазин'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='productattributes',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('url_at_shop',)},
        ),
    ]
